name = "SOG: Prairie Fire - Custom Faction Example"
mainprefix = "vn"
prefix = "cfe"
author = "Savage Game Design"

[files]
include = [
    "LICENSE",
    "README.md",
]
exclude = ["*.psd", "*.png", "*.tga", "*.hpp"]

[version]
path = "addons/core_c/script_version.hpp" # Default

[hemtt.launch]
workshop = [
    "2369477168", # ADT
]
dlc = [
    "S.O.G. Prairie Fire",
]
